// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVkFt20d15Tdba9gR-xQ-nb19RkFborPc',
    appId: '1:723779577406:web:64f9e14b536bf0fc7b136f',
    messagingSenderId: '723779577406',
    projectId: 'flutter-firebase-dersler-48f99',
    authDomain: 'flutter-firebase-dersler-48f99.firebaseapp.com',
    storageBucket: 'flutter-firebase-dersler-48f99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtx585PmeApDsvDEmbAL80Y5S4Bjc9oPs',
    appId: '1:723779577406:android:c92e699c842d0e6b7b136f',
    messagingSenderId: '723779577406',
    projectId: 'flutter-firebase-dersler-48f99',
    storageBucket: 'flutter-firebase-dersler-48f99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARFdADDn4g-NMFAcmU_0ij22tdqbErO-o',
    appId: '1:723779577406:ios:f9980f79fb7f1a027b136f',
    messagingSenderId: '723779577406',
    projectId: 'flutter-firebase-dersler-48f99',
    storageBucket: 'flutter-firebase-dersler-48f99.appspot.com',
    iosClientId: '723779577406-du2r4geb5mt9ev71lo7n6qkitc40om27.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
